const categorySelect = document.getElementById('category');
const processDetails = document.getElementById('process-details');

const segregationProcess = {
    cooling: "In the realm of cooling equipment, effective segregation is pivotal for enhancing efficiency and energy conservation. Employing temperature sensors and dynamic control systems, this approach maintains optimal operating conditions. If a component runs excessively hot, adjustments, like altering workload or activating additional cooling mechanisms, are initiated. A different strategy involves load balancing algorithms to evenly distribute cooling workloads across multiple units. This ensures that no unit is overburdened, promoting equipment longevity. Additionally, predictive maintenance utilizing machine learning predicts component failures, facilitating planned maintenance, minimizing costly downtime, and guaranteeing reliability. In the IT sector, where uninterrupted cooling is vital, these techniques play a crucial role in equipment optimization.",
    computers: "The segregation process for computers involves categorizing and managing them based on various criteria. Computers are typically grouped according to their usage, age, and performance. This segregation allows for optimized resource allocation and maintenance. For instance, older computers may be designated for less demanding tasks, while high-performance machines are allocated to resource-intensive applications. Additionally, segregation aids in implementing security measures, as sensitive data can be stored on isolated systems. Regular maintenance schedules can be tailored to the specific needs of each group, ensuring prolonged operational efficiency. By segregating computers effectively, organizations can enhance productivity, security, and resource management in their IT infrastructure.",
    solar: "Segregation of solar panels is vital for efficiency and output optimization. Solar panels are grouped based on factors like their orientation, age, and efficiency. Panels with similar attributes are placed together to ensure uniform performance. This helps prevent shading, which can significantly reduce energy production. Moreover, regular maintenance and cleaning schedules are established for each group to maintain peak efficiency. Advanced monitoring systems can identify underperforming panels, allowing for timely replacements. By segregating and managing solar panels effectively, the overall energy production is maximized, making it a crucial practice in the renewable energy industry.",
    led: "The segregation process for LED bulbs is essential for efficient inventory management and ensuring optimal lighting performance. LED bulbs are typically categorized based on factors such as wattage, color temperature, and lifespan. This segregation allows for precise selection of bulbs suitable for various applications. For instance, bulbs with higher wattage may be designated for areas that require brighter lighting, while those with specific color temperatures are chosen to create desired ambiances. Additionally, LED bulbs can be sorted by their estimated lifespan, ensuring that replacements are planned in advance. By segregating LED bulbs effectively, businesses and homeowners can maximize energy efficiency, create tailored lighting solutions, and reduce maintenance costs.",
    vending: "The segregation process for vending machines is a crucial aspect of efficient operation and management. Vending machines are typically categorized based on factors like product type, location, and customer demand. Grouping machines by product type ensures that each machine carries the appropriate selection of goods, tailored to customer preferences. Location-based segregation helps in optimizing placement to maximize foot traffic and sales. Furthermore, monitoring customer demand patterns assists in allocating popular products to high-traffic areas. Maintenance schedules and restocking strategies can also be customized for each group, improving overall machine performance and profitability. Effective segregation of vending machines is key to delivering the right products to the right customers at the right locations.",
};

categorySelect.addEventListener('change', () => {
    const selectedCategory = categorySelect.value;
    processDetails.textContent = segregationProcess[selectedCategory];
});
